const swaggerAutogen = require("swagger-autogen")();
const definitions = require("./definitions");

const doc = {
  info: {
    version: "0.0.1",
    title: "Fugger API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/api",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  definitions,
};

const outputFile = `${__dirname}/output.json`;
const endpointsFiles = [];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  // eslint-disable-next-line global-require
  require("../index"); // Your project's root file
});
